[package]
name = "ch2"
version = "0.1.0"
authors = ["Laura Lindzey <lindzey@gmail.com>"]
edition = "2018"

[lib]
name = "pfds"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
